### ISSUE TITLE
Number of threads

### ISSUE THREAD

**Issue by ari9609** [mooreryan/divnet-rs#1]
Hi, I’m trying to set number of threads in divnet-rs
But when I run the exact code that is in divnet-rs book, it tells me there’s no such a file or directory with the name config.toml
This is the code: OPENBLAS_NUM_THREADS=1 divnet-rs /path/to/config.toml

**Comment by mooreryan** [comment]
Hi @ari9609, sorry if it was unclear in the docs, but you will still have to create a config file before running `divnet-rs`.  After creating the config file, replace `/path/to/config.toml` with the real path to the config file you created.

For info about creating a config file see https://mooreryan.github.io/divnet-rs-book/config_files.html.

For some examples of using `divnet-rs`, see:

* [A couple of full examples](https://github.com/mooreryan/divnet-rs/tree/master/test_files)
* [A short tutorial](https://mooreryan.github.io/divnet-rs-book/lee_data_walkthrough.html)
