### ISSUE TITLE
Using DivNet-rs results as input for Breakaway and Hypothesis Testing 

### ISSUE THREAD

**Issue by benyoung93** [mooreryan/divnet-rs#2]
Good morning Ryan 
First of all thank you so so so much for this implementation of DivNet, it is truly a lifesaver for my large ASV and sample datasets :) 

I had a quick query. So I have followed all the vignette, as well as the r script to get this data back into R (line 36 of 3_import_divnet_rs_data.R). I have also used this tidyverse to generate a cleaner summarised data frame with all metadata and divnet-rs results 

```{r}
tibble(names = names(rep0_shannon),
       shannon = rep0_shannon) %>%
  left_join(reps_shannon_error %>%
              as.data.frame %>%
              rownames_to_column("names")) %>%
  mutate(ciupper = shannon +( 2 * sd),
         cilower = shannon - (2 * sd)) %>% 
  filter(names %in% rownames(METADATA)) %>% 
  inner_join(METADATA %>% 
              rownames_to_column(var = "names")) %>% 
  column_to_rownames(var = "names") -> alpha_shannon_inoc
```

I now want to do hypothesis testing and I just want to make sure I am using the correct data for Breakaway (another amazing Amy Willis package). 

So far I have 

```{r}
betta(chats = shannon_estimates,  *this is the values from rep0_shannon*
           ses = sqrt(shannon_variance),  *this is using variacne from generated rep_shannon_error)
            X = model ()
```

I think I have utilised the right information but just wanted to double check this :). 

thank you for any and all help and I look forward to your response. 

Tagging @adw96 also :) 

Benjamin

**Comment by mooreryan** [comment]
Hi Benjamin, apologies for the delayed response, but I wanted to go back to the DivNet R package to make sure about this.  I will put the links to the relevant parts of the code so you may check as well.

Let me know if you have any other questions!

## Short answer

You take the variance of the alpha diversity estimates, then take the square root of that and pass it to the `betta` function.  (Which seems to be what you're doing here!)

## Going through divnet code

[Here](https://github.com/adw96/DivNet/blob/3de09231e41ac8f9602d25ecce3e11dd6603c2f4/vignettes/getting-started.Rmd#L190) is how the vignette uses the `betta` function.  They pass the square root of the the shannon variance of the alpha diversity estimates to the `ses` parameter of `betta` function.

And then [here, in the way DivNet itself uses the betta package](https://github.com/adw96/DivNet/blob/3219c3f0e2b7536be90f52014370167cb9a2627e/R/s3functions.R#L81) you can see that the "error" is put directly into the second argument of `betta`.  (That's `x$error`)

The `error` slot is filled in [here](https://github.com/adw96/DivNet/blob/3de09231e41ac8f9602d25ecce3e11dd6603c2f4/R/divnet_main.R#L162) (sqrt of the shannon-variance).  And that is calculated [here](https://github.com/adw96/DivNet/blob/3de09231e41ac8f9602d25ecce3e11dd6603c2f4/R/divnet_main.R#L154).

[Here](https://github.com/adw96/DivNet/blob/3de09231e41ac8f9602d25ecce3e11dd6603c2f4/R/estimate_diversity.R#L73) you can see `get_diversity_variance` fills in `shannon-variance` using the `var` function (variance).

**Comment by benyoung93** [comment]
Hi Ryan 

Yes so I went through all functions as well and it seems I am using the right information. The main one I was double checking was actually the chats argument (which is the reps0_shannon in divnet-rs, the estimates), but it seems I am using both correctly which is fantastic. 

Please do not apologise for the delayed response, the help is truly appreciated :). 

Benjamin

**Comment by mooreryan** [comment]
Ah yes, the `chats` parameter is correct too. 

I misread your original comment thinking it was about the `ses` parameter, as that is the parameter that I remember going through and triple checking when I was working on this implementation. 

I should probably update the documentation to say all of this 😄

**Comment by benyoung93** [comment]
HI Ryan 

All good, the SES was actually more straight forward than the chats for me 😂😂😂

I think a quick section on the inputs for Hyp testing with betta would be useful in the documentation. It is not overly complex but it was more for my peace of mind 😂😂. 

Thanks for the quick responses and, again, this amazing implementation. I have 320 samples with ~8000 ASVs so this was a lifesaver. Im sure you probably saw my suggestion on the DivNet main page to include a section to your implementation as it was hidden away in the issues originally. I think Amy has included now 🙌🙌🙌🙌🙌

Benjamin

**Comment by mooreryan** [comment]
No problem, glad the program is working out for you. I have similar sized data sets to yours...it's quite helpful for that sized data!!

Let me know of any other issues you run into!

**Comment by adw96** [comment]
Thanks to both of you -- I'm late to the party as usual. Ryan, David (@ailurophilia) is the StatDivLab DivNet hypothesis testing expert, so if you want another pair of eyes on any documentation you have/intend for hypothesis testing with divnet-rs please tag both David and I and we can give it a once-over. 

and yes, this fantastic package is linked to from the DivNet homepage now 💯
