### ISSUE TITLE
Error when algorithm moves to first replicate

### ISSUE THREAD

**Issue by ch16S** [mooreryan/divnet-rs#5]
Hello there,

Great job on this rust implementation of DivNet !

I have run some initial tests with divnet-rs on my data.
I can get one dataset to run successfully. 

However, another dataset will complete the first set of EM iterations - then when it gets to the replicate1 it prints this error: 

`thread 'main' panicked at 'assert_abs_diff_eq!(prob_sum, 1., epsilon = 1e-6)

    left  = NaN
    right = 1.0

', /home/ubuntu/divnet-rs/src/multinomial.rs:7:5
`
If I set replicate = 0 it will run to completion. 
There is about 800 samples and 700 taxa in the dataset. 

My rust literacy is practically zero, so I thought I'd see if you help me out.  

Cheers,
Chris

**Comment by mooreryan** [comment]
Interesting...it looks like you have some NaNs being generated in your probabilities.

Would you be able to show me how you prepared the input data (and if possible send me the input files as well)?
